SNILS_LENGTH                = 16
NAME_LENGTH                 = 255
EMPLOYEE_NAME_LENGTH        = NAME_LENGTH
DEPARTMENT_NAME_LENGTH      = NAME_LENGTH
ACTIVITY_SPHERE_NAME_LENGTH = NAME_LENGTH
EMPLOYEE_ROLE_NAME_LENGTH   = NAME_LENGTH
RIGHTS_NAME_LENGTH          = NAME_LENGTH
EMPL_OPER_TYPE_NAME_LENGTH  = NAME_LENGTH
TASK_PRIORITY_NAME_LENGTH   = NAME_LENGTH
TASK_NAME_LENGTH            = NAME_LENGTH
TASK_STATE_NAME_LENGTH      = NAME_LENGTH
EQ_MODEL_NAME_LENGTH        = NAME_LENGTH
EQ_NAME_LENGTH              = NAME_LENGTH
SN_NAME_LENGTH              = NAME_LENGTH
EQ_OPER_TYPE_NAME_LENGTH    = NAME_LENGTH
NODE_CATEGORY_NAME_LENGTH   = NAME_LENGTH
DETAIL_MODEL_NAME_LENGTH    = NAME_LENGTH
 
RIGHTS_LENGTH               = 8

PHONE_LENGTH                = 32
EMPLOYEE_PHONE_LENGTH       = PHONE_LENGTH
DEPARTMENT_PHONE_LENGTH     = PHONE_LENGTH
 
ADDR_LENGTH                 = 512
EMPLOYEE_ADDR_LENGTH        = ADDR_LENGTH
DEPARTMENT_ADDR_LENGTH      = ADDR_LENGTH
EQ_ADDR_LENGTH              = ADDR_LENGTH
 
LOGIN_LENGTH                = 64
EMPLOYEE_LOGIN_LENGTH       = LOGIN_LENGTH
 
PASSWORD_LENGTH             = 128
EMPLOYEE_PASSWORD_LENGTH    = PASSWORD_LENGTH

COMMENT                     = 512
EQ_ASS_NAME_LENGTH          = COMMENT

